spring:
  cloud:
    gateway:
      routes:
        - id: api-catalogs
          uri: http://localhost:9000
          predicates:
            - Path=/gateway/api/catalogs/**
          filters:
            - StripPrefix=3
            - name: Authentication
              args:
                roles:
                  - CUSTOMER
                  - EXECUTIVE
        - id: api-users
          uri: http://localhost:9004
          predicates:
            - Path=/gateway/api/users/**
          filters:
            - StripPrefix=3

services:
  internal:
    session-checking: http://localhost:9004/user/session-checking

kyc-config:
  encryption:
    enabled: false
    white-list:
      - 127.0.0.2
    aes:
      key-store: classpath:keystore.p12
      key-alias: kyc-gtw-key
      key-password: test123
      key-store-type: PKCS12
      key-store-password: test123