spring:
  ssl:
    bundle:
      jks:
        kyc-bundle:
          truststore:
            location: ${kyc.config.keystore.gateway.path}
            password: ${kyc.config.keystore.gateway.secret}
  cloud:
    gateway:
      httpclient:
        ssl:
          ssl-bundle: kyc-bundle
      routes:
        - id: api-catalogs
          uri: ${api-domain}
          predicates:
            - Path=/gateway/api/catalogs/**
          filters:
            - StripPrefix=1
            - name: Authentication
              args:
                roles:
                  - CUSTOMER
                  - EXECUTIVE
        - id: api-customers-id
          uri: ${api-domain}
          predicates:
            - Path=/gateway/api/customers/customer/info
          filters:
            - StripPrefix=1
            - RewritePath=/api/customers/customer/info, /api/customers/customer-data
            - name: CacheRequestBody
              args:
                bodyClass: com.kyc.gateway.model.GraphqlRestReq
            - name: Authentication
              args:
                roles:
                  - CUSTOMER
            - name: CustomerQueryGraphql
              args:
                regex: "customer\\s*\\{"
                replacement: "customer(filter: {id: %s}){"
                operation: "customerById"
        - id: api-customers
          uri: ${api-domain}
          predicates:
            - Path=/gateway/api/customers/**
          filters:
            - StripPrefix=1
            - name: Authentication
              args:
                roles:
                  - EXECUTIVE
        - id: api-campaigns-customer
          uri: ${api-domain}
          predicates:
            - Path=/gateway/api/campaigns/customer/{campaign}/offers/**
          filters:
            - StripPrefix=1
            - name: Authentication
              args:
                roles:
                  - CUSTOMER
                  - EXECUTIVE
        - id: api-campaigns
          uri: ${api-domain}
          predicates:
            - Path=/gateway/api/campaigns/**
          filters:
            - StripPrefix=1
            - name: Authentication
              args:
                roles:
                  - EXECUTIVE
        - id: api-notifications-customer
          uri: ${api-domain}
          predicates:
            - Method=GET
            - Path=/gateway/api/notifications/**
          filters:
            - StripPrefix=1
            - name: Authentication
              args:
                roles:
                  - CUSTOMER
        - id: api-notifications
          uri: ${api-domain}
          predicates:
            - Path=/gateway/api/notifications/**
          filters:
            - StripPrefix=1
            - name: Authentication
              args:
                roles:
                  - EXECUTIVE
        - id: api-users-open
          uri: ${api-domain}
          predicates:
            - Path=/gateway/api/users/customer/sign-up,/gateway/api/users/user/sign-in, /gateway/api/users/user/sign-out
          filters:
            - StripPrefix=1
        - id: api-users
          uri: ${api-domain}
          predicates:
            - Path=/gateway/api/users/user/**
          filters:
            - StripPrefix=1
            - name: Authentication
              args:
                roles:
                  - CUSTOMER
                  - EXECUTIVE
        - id: api-tracking-customers
          uri: ${api-domain}
          predicates:
            - Method=POST
            - Path=/gateway/api/tracking/customers/**
          filters:
            - StripPrefix=1
            - name: Authentication
              args:
                roles:
                  - CUSTOMER
        - id: api-tracking
          uri: ${api-domain}
          predicates:
            - Path=/gateway/api/tracking/executives/**,/gateway/api/tracking/customer/v1/actions
          filters:
            - StripPrefix=1
            - name: Authentication
              args:
                roles:
                  - EXECUTIVE
        - id: api-bills
          uri: ${api-domain}
          predicates:
            - Path=/gateway/api/bills/**
          filters:
            - StripPrefix=1
            - name: Authentication
              args:
                roles:
                  - CUSTOMER
                  - EXECUTIVE
        - id: api-customer-application
          uri: ${api-domain}
          predicates:
            - Path=/gateway/api/customer-application/**
          filters:
            - StripPrefix=1
            - name: Authentication
              args:
                roles:
                  - CUSTOMER
                  - EXECUTIVE

api-domain: https://api.kyc-project.dev.com

services:
  internal:
    session-checking: ${api-domain}/api/users/user/session-checking

kyc-config:
  encryption:
    enabled: true
    white-list: ${kyc.config.whitelist.gateway}
    aes:
      key-store: ${kyc.config.keystore.gateway.path}
      key-alias: kyc-gtw-key
      key-password: ${kyc.config.keystore.gateway.secret}
      key-store-type: PKCS12
      key-store-password: ${kyc.config.keystore.gateway.secret}

logging:
  file:
    name: /opt/kyc/logs/${spring.application.name}-${instance}.log
  logback:
    rollingpolicy:
      file-name-pattern: /opt/kyc/logs/${spring.application.name}-${instance}/%d{yyyy-MM-dd}.%i.log.gz
      max-file-size: 50MB
      max-history: 3